### ISSUE TITLE
no command found scan

### ISSUE THREAD

**Issue by djdanielsson** [dills122/MTG-Card-Analyzer#52]
I have followed your instructions but there is no scan command, so I am not sure what I did wrong.

**Comment by djdanielsson** [comment]
also when running create-needs-attention.sql script I get "ERROR 1170 (42000): BLOB/TEXT column 'NameImage' used in key specification without a key length" error.

**Comment by dills122** [comment]
I added a new section on the read me giving a basic first command to run. 
https://github.com/dills122/MTG-Card-Analyzer#first-test-run

Were you running it in the repo like this?
```
node index.js scan ./path/to/file
```

**Comment by dills122** [comment]
Also it looks like there is a bug in the `create-needs-attention.sql` due to trying to use the `NameImage` column in a compound key for the table. as a work around for now you can just remove that column from this line in the file.
https://github.com/dills122/MTG-Card-Analyzer/blob/5ca254c061695b5ee6bc728059700569a261fd79/src/data/scripts/sql/create-needs-attention.sql#L18

**Comment by djdanielsson** [comment]
thanks for the help
